-- Seed: public.healthfacility_raw_map  (raw source spelling -> facility_id)
-- Generated from the 2026 Chikungunya database facility columns.
-- Whole (trimmed, lower-cased) source cell is the lookup key, matching
-- chikungunya_pipeline.normalize._key(). Idempotent via ON CONFLICT.

INSERT INTO public.healthfacility_raw_map (raw_value, facility_id)
SELECT v.raw_value, f.facility_id
FROM (VALUES
  ('aed', 'Dr A. G. Jeetoo Hospital'),
  ('aed dr ag jh', 'Dr A. G. Jeetoo Hospital'),
  ('aed jh', 'Dr A. G. Jeetoo Hospital'),
  ('aed uns', 'Dr A. G. Jeetoo Hospital'),
  ('ag jh', 'Dr A. G. Jeetoo Hospital'),
  ('agjh', 'Dr A. G. Jeetoo Hospital'),
  ('agjh a&e', 'Dr A. G. Jeetoo Hospital'),
  ('agjh uns', 'Dr A. G. Jeetoo Hospital'),
  ('agjh wd 3.1', 'Dr A. G. Jeetoo Hospital'),
  ('agkh uns', 'Dr A. G. Jeetoo Hospital'),
  ('dr a g jeetoo hospital', 'Dr A. G. Jeetoo Hospital'),
  ('dr a g jh in ward 3.1', 'Dr A. G. Jeetoo Hospital'),
  ('dr a g jh in ward 3.2', 'Dr A. G. Jeetoo Hospital'),
  ('dr ag jh', 'Dr A. G. Jeetoo Hospital'),
  ('fast track', 'Dr A. G. Jeetoo Hospital'),
  ('fast track agjh', 'Dr A. G. Jeetoo Hospital'),
  ('fast track jh', 'Dr A. G. Jeetoo Hospital'),
  ('fast tract', 'Dr A. G. Jeetoo Hospital'),
  ('jeetoo', 'Dr A. G. Jeetoo Hospital'),
  ('jeetoo hospital', 'Dr A. G. Jeetoo Hospital'),
  ('jeetoo hospital(28/02-02/03)', 'Dr A. G. Jeetoo Hospital'),
  ('jh', 'Dr A. G. Jeetoo Hospital'),
  ('jh 1.1', 'Dr A. G. Jeetoo Hospital'),
  ('jh a&e', 'Dr A. G. Jeetoo Hospital'),
  ('jh aed', 'Dr A. G. Jeetoo Hospital'),
  ('jh fast tract', 'Dr A. G. Jeetoo Hospital'),
  ('jh uns', 'Dr A. G. Jeetoo Hospital'),
  ('jh unsorted', 'Dr A. G. Jeetoo Hospital'),
  ('jh ward 3-6', 'Dr A. G. Jeetoo Hospital'),
  ('jh wd 3.1', 'Dr A. G. Jeetoo Hospital'),
  ('jhaed', 'Dr A. G. Jeetoo Hospital'),
  ('jnh unsorted opd', 'Dr A. G. Jeetoo Hospital'),
  ('paeds ft', 'Dr A. G. Jeetoo Hospital'),
  ('paeds opd jh', 'Dr A. G. Jeetoo Hospital'),
  ('trauma & emergency agjh', 'Dr A. G. Jeetoo Hospital'),
  ('uns jeetoo', 'Dr A. G. Jeetoo Hospital'),
  ('uns jh', 'Dr A. G. Jeetoo Hospital'),
  ('unsorted', 'Dr A. G. Jeetoo Hospital'),
  ('unsorted jh', 'Dr A. G. Jeetoo Hospital'),
  ('unsorted opd jnh', 'Dr A. G. Jeetoo Hospital'),
  ('unsorted paed', 'Dr A. G. Jeetoo Hospital'),
  ('unsorted ped vh', 'Dr A. G. Jeetoo Hospital'),
  ('ward 3.1 @ jh', 'Dr A. G. Jeetoo Hospital'),
  ('wd 2.4 @ dr ag jh', 'Dr A. G. Jeetoo Hospital'),
  ('wd 3-2 @ jh', 'Dr A. G. Jeetoo Hospital'),
  ('wd 3.1 @ dr ag jh', 'Dr A. G. Jeetoo Hospital'),
  ('aed vh', 'Victoria Hospital'),
  ('unsorted vh', 'Victoria Hospital'),
  ('unsortedvh', 'Victoria Hospital'),
  ('vh', 'Victoria Hospital'),
  ('vh 16b', 'Victoria Hospital'),
  ('vh a&e', 'Victoria Hospital'),
  ('vh aed', 'Victoria Hospital'),
  ('vh c12', 'Victoria Hospital'),
  ('vh lab', 'Victoria Hospital'),
  ('vh medical', 'Victoria Hospital'),
  ('vh paeds', 'Victoria Hospital'),
  ('vh pead uns', 'Victoria Hospital'),
  ('vh peads uns', 'Victoria Hospital'),
  ('vh uns', 'Victoria Hospital'),
  ('vh unsorted', 'Victoria Hospital'),
  ('vh ward 16b', 'Victoria Hospital'),
  ('vh ward 4', 'Victoria Hospital'),
  ('vh ward f11', 'Victoria Hospital'),
  ('vh, wellkin hospital', 'Victoria Hospital'),
  ('victoria', 'Victoria Hospital'),
  ('victoria hospital', 'Victoria Hospital'),
  ('jnh', 'Jawaharlal Nehru Hospital'),
  ('jnh a&e', 'Jawaharlal Nehru Hospital'),
  ('jnh unsorted', 'Jawaharlal Nehru Hospital'),
  ('jnh ward 0-5', 'Jawaharlal Nehru Hospital'),
  ('jnh-unsorted', 'Jawaharlal Nehru Hospital'),
  ('ssrnh', 'Sir Seewoosagur Ramgoolam National Hospital'),
  ('ssrnh ed 2-2', 'Sir Seewoosagur Ramgoolam National Hospital'),
  ('ssrnh unsorted', 'Sir Seewoosagur Ramgoolam National Hospital'),
  ('ssrnh ward 2-1', 'Sir Seewoosagur Ramgoolam National Hospital'),
  ('saj hospital', 'Sir Anerood Jugnauth Hospital'),
  ('sajh', 'Sir Anerood Jugnauth Hospital'),
  ('sajh uns', 'Sir Anerood Jugnauth Hospital'),
  ('new souillac hospital', 'New Souillac Hospital'),
  ('nsh', 'New Souillac Hospital'),
  ('nsh a&e', 'New Souillac Hospital'),
  ('souillac hospital', 'New Souillac Hospital'),
  ('mahebourg hospital', 'Mahebourg Hospital'),
  ('long mountain hospital', 'Long Mountain Hospital'),
  ('welkin', 'Wellkin Hospital'),
  ('welkin hospital', 'Wellkin Hospital'),
  ('wellkin', 'Wellkin Hospital'),
  ('wellkin clinic', 'Wellkin Hospital'),
  ('wellkin hospital', 'Wellkin Hospital'),
  ('wellkin hospital nicu', 'Wellkin Hospital'),
  ('wellkin hospital room 642', 'Wellkin Hospital'),
  ('wellkin level 4', 'Wellkin Hospital'),
  ('wellkinn', 'Wellkin Hospital'),
  ('c care darne', 'C-Care Darné'),
  ('c care darney', 'C-Care Darné'),
  ('c clab darne', 'C-Care Darné'),
  ('c darne', 'C-Care Darné'),
  ('c lab cdarne', 'C-Care Darné'),
  ('c lab darne', 'C-Care Darné'),
  ('c-care darne', 'C-Care Darné'),
  ('c-care darney', 'C-Care Darné'),
  ('cdarne', 'C-Care Darné'),
  ('clab darne', 'C-Care Darné'),
  ('darne', 'C-Care Darné'),
  ('darne clinic', 'C-Care Darné'),
  ('c care', 'C-Care'),
  ('c care grand baie', 'C-Care'),
  ('c care mont choisy', 'C-Care'),
  ('c care welkin', 'C-Care'),
  ('c care wellkin', 'C-Care'),
  ('c care wellkinn', 'C-Care'),
  ('c care, grand bay', 'C-Care'),
  ('c care, moka', 'C-Care'),
  ('c-care', 'C-Care'),
  ('ccare', 'C-Care'),
  ('premium care', 'C-Care'),
  ('premium care clinic', 'C-Care'),
  ('premiun care clinic', 'C-Care'),
  ('bon pasteur', 'Clinique du Bon Pasteur'),
  ('bon pasteur clinic', 'Clinique du Bon Pasteur'),
  ('clinic bon pasteur', 'Clinique du Bon Pasteur'),
  ('clinique bon pasteur', 'Clinique du Bon Pasteur'),
  ('nouvelle clinic du bon pasteur', 'Clinique du Bon Pasteur'),
  ('nouvelle clinique du bon pasteur', 'Clinique du Bon Pasteur'),
  ('life forbach', 'Life Medical Clinic'),
  ('life med clinic', 'Life Medical Clinic'),
  ('life medical clinic bon pasteur', 'Life Medical Clinic'),
  ('life nova', 'Life Medical Clinic'),
  ('life nova plus', 'Life Medical Clinic'),
  ('life nova plus, tamarin', 'Life Medical Clinic'),
  ('life nova tamarin', 'Life Medical Clinic'),
  ('clinic mauricienne', 'La Clinique Mauricienne'),
  ('clinique mauricienne', 'La Clinique Mauricienne'),
  ('clinique mauritian', 'La Clinique Mauricienne'),
  ('la clinique mauricienne', 'La Clinique Mauricienne'),
  ('royal green', 'Royal Green Hospital'),
  ('royal green clinic', 'Royal Green Hospital'),
  ('royal green hospital', 'Royal Green Hospital'),
  ('artemis', 'Artemis Hospital'),
  ('artemis hosp', 'Artemis Hospital'),
  ('artemis hospital', 'Artemis Hospital'),
  ('smc', 'Stanley Mediclinic'),
  ('stanley mc', 'Stanley Mediclinic'),
  ('stanley medi', 'Stanley Mediclinic'),
  ('stanley mediclinic', 'Stanley Mediclinic'),
  ('cmc', 'Coromandel Mediclinic'),
  ('coramandel mediclinic', 'Coromandel Mediclinic'),
  ('coro medi', 'Coromandel Mediclinic'),
  ('coromandal mc', 'Coromandel Mediclinic'),
  ('coromandel chc', 'Coromandel Mediclinic'),
  ('coromandel mc', 'Coromandel Mediclinic'),
  ('coromandel medi clinic', 'Coromandel Mediclinic'),
  ('coromandel mediclinic', 'Coromandel Mediclinic'),
  ('coromendel medi', 'Coromandel Mediclinic'),
  ('mediclinic coromandel', 'Coromandel Mediclinic'),
  ('p.riviere mc', 'Petite Rivière Mediclinic'),
  ('petite riv mediclinic', 'Petite Rivière Mediclinic'),
  ('petite riviere ahc', 'Petite Rivière Mediclinic'),
  ('petite riviere mc', 'Petite Rivière Mediclinic'),
  ('petite riviere mediclinic', 'Petite Rivière Mediclinic'),
  ('pte riv mc', 'Petite Rivière Mediclinic'),
  ('hyderkhan mc', 'Hyderkhan Mediclinic'),
  ('hyderkhan mediclinic', 'Hyderkhan Mediclinic'),
  ('grand bois mediclinic', 'Grand Bois Mediclinic'),
  ('quartier militaire mediclinic', 'Quartier Militaire Mediclinic'),
  ('l''escalier mc', 'L''Escalier Mediclinic'),
  ('l''escalier medi clinic', 'L''Escalier Mediclinic'),
  ('lescalier mc', 'L''Escalier Mediclinic'),
  ('floreal mediclinic', 'Floréal Mediclinic'),
  ('goodlands mediclinic', 'Goodlands Mediclinic'),
  ('bel air mediclinic', 'Bel Air Mediclinic'),
  ('bel air riv seche mediclinic', 'Bel Air Mediclinic'),
  ('mediclinic plaine verte', 'Plaine Verte Mediclinic'),
  ('city clinic grand baie', 'City Clinic'),
  ('city clinic p.louis', 'City Clinic'),
  ('odelette leal chc', 'Odette Leal CHC'),
  ('odette chc', 'Odette Leal CHC'),
  ('odette leal', 'Odette Leal CHC'),
  ('odette leal chc', 'Odette Leal CHC'),
  ('michael leal chc', 'Michael Leal CHC'),
  ('roche bois chc', 'Roche Bois CHC'),
  ('pailles chc', 'Pailles CHC'),
  ('pailles east chc', 'Pailles CHC'),
  ('albion chc', 'Albion CHC'),
  ('saint croix chc', 'Sainte Croix CHC'),
  ('tombeau baie chc', 'Tombeau Bay CHC'),
  ('tombeau bay chc', 'Tombeau Bay CHC'),
  ('phoenix chc', 'Phoenix CHC'),
  ('cap malheureux', 'Cap Malheureux CHC'),
  ('cap malheureux chc', 'Cap Malheureux CHC'),
  ('trefles chc', 'Trèfles CHC'),
  ('pas chc', 'Pointe aux Sables CHC'),
  ('bambou ahc', 'Bambous AHC'),
  ('bambous', 'Bambous AHC'),
  ('bambous ahc', 'Bambous AHC'),
  ('lady twining', 'Lady Twining AHC'),
  ('lady twining ahc', 'Lady Twining AHC'),
  ('lady twinng ahc', 'Lady Twining AHC'),
  ('lady twinning', 'Lady Twining AHC'),
  ('lady twinning ahc', 'Lady Twining AHC'),
  ('lady twinning chc', 'Lady Twining AHC'),
  ('new grove ahc', 'New Grove AHC'),
  ('tyack ahc', 'Tyack AHC'),
  ('bouloux ahc', 'Bouloux AHC'),
  ('c grenier ahc', 'Chemin Grenier AHC'),
  ('c.grenier ahc', 'Chemin Grenier AHC'),
  ('ch.grenier ahc', 'Chemin Grenier AHC'),
  ('chemin grenier ahc', 'Chemin Grenier AHC'),
  ('dr yves cantin ahc', 'Yves Cantin CHC'),
  ('ycch', 'Yves Cantin CHC'),
  ('yue cantin chc', 'Yves Cantin CHC'),
  ('yues cantin chc', 'Yves Cantin CHC'),
  ('yve cartin', 'Yves Cantin CHC'),
  ('yves cantin', 'Yves Cantin CHC'),
  ('beau bassin ahc', 'Beau Bassin AHC'),
  ('r.hill ahc', 'Rose Hill AHC'),
  ('rh ahc', 'Rose Hill AHC'),
  ('rose hill ahc', 'Rose Hill AHC'),
  ('qbornes ahc', 'Quatre Bornes AHC'),
  ('st pierre lhc', 'St Pierre LHC'),
  ('cpe ahc', 'Curepipe AHC'),
  ('c clab wellkinn', 'C-Lab'),
  ('c lab', 'C-Lab'),
  ('c lab albion', 'C-Lab'),
  ('c lab wellkin', 'C-Lab'),
  ('c lab wellkin hospital', 'C-Lab'),
  ('c lab wellkin hospital, moka', 'C-Lab'),
  ('c lab wellkinn', 'C-Lab'),
  ('c lab wellkn', 'C-Lab'),
  ('c lab welln', 'C-Lab'),
  ('c-lab', 'C-Lab'),
  ('clab', 'C-Lab'),
  ('clab albion', 'C-Lab'),
  ('clab wellkinn', 'C-Lab'),
  ('darne clab', 'C-Lab'),
  ('biosante', 'Biosanté Laboratory'),
  ('novalab', 'Novalab'),
  ('novalab phoenix', 'Novalab'),
  ('lab medisave quatre bornes', 'Medisave'),
  ('medisave', 'Medisave'),
  ('medisave clinic', 'Medisave'),
  ('medisave lab', 'Medisave'),
  ('lab villes soeurs', 'Laboratoire des Villes Soeurs'),
  ('laboratoire des villes soeurs', 'Laboratoire des Villes Soeurs'),
  ('laboratoire medical des ville soeurs', 'Laboratoire des Villes Soeurs'),
  ('clinic muller', 'Clinic Muller')
) AS v(raw_value, facility_name)
JOIN public.healthfacilities f ON f.facility_name = v.facility_name
ON CONFLICT (raw_value) DO UPDATE SET facility_id = EXCLUDED.facility_id;
