-- Seed: public.healthfacilities  (canonical Mauritius healthcare facilities)
-- Generated from the 2026 Chikungunya database facility columns.
-- Idempotent: ON CONFLICT (facility_name) DO UPDATE keeps type/region fresh.

INSERT INTO public.healthfacilities (facility_name, facility_type, health_region) VALUES
  ('Dr A. G. Jeetoo Hospital', 'Regional Hospital', 'Port Louis'),
  ('Victoria Hospital', 'Regional Hospital', 'Plaines Wilhems (Candos)'),
  ('Jawaharlal Nehru Hospital', 'Regional Hospital', 'Grand Port (Rose Belle)'),
  ('Sir Seewoosagur Ramgoolam National Hospital', 'Regional Hospital', 'Pamplemousses'),
  ('Sir Anerood Jugnauth Hospital', 'Regional Hospital', 'Flacq'),
  ('New Souillac Hospital', 'District Hospital', 'Savanne (Souillac)'),
  ('Mahebourg Hospital', 'District Hospital', 'Grand Port'),
  ('Long Mountain Hospital', 'District Hospital', 'Pamplemousses'),
  ('Wellkin Hospital', 'Private Hospital/Clinic', 'Moka'),
  ('C-Care Darné', 'Private Hospital/Clinic', 'Floréal'),
  ('C-Care', 'Private Hospital/Clinic', NULL),
  ('Clinique du Bon Pasteur', 'Private Hospital/Clinic', 'Rose Hill'),
  ('Life Medical Clinic', 'Private Hospital/Clinic', NULL),
  ('La Clinique Mauricienne', 'Private Hospital/Clinic', 'Rose Hill'),
  ('Royal Green Hospital', 'Private Hospital/Clinic', NULL),
  ('Artemis Hospital', 'Private Hospital/Clinic', NULL),
  ('Stanley Mediclinic', 'Private Mediclinic', 'Rose Hill'),
  ('Coromandel Mediclinic', 'Private Mediclinic', 'Port Louis'),
  ('Petite Rivière Mediclinic', 'Private Mediclinic', 'Black River'),
  ('Hyderkhan Mediclinic', 'Private Mediclinic', NULL),
  ('Grand Bois Mediclinic', 'Private Mediclinic', 'Grand Port'),
  ('Quartier Militaire Mediclinic', 'Private Mediclinic', 'Moka'),
  ('L''Escalier Mediclinic', 'Private Mediclinic', 'Grand Port'),
  ('Floréal Mediclinic', 'Private Mediclinic', 'Plaines Wilhems'),
  ('Goodlands Mediclinic', 'Private Mediclinic', 'Rivière du Rempart'),
  ('Bel Air Mediclinic', 'Private Mediclinic', 'Flacq'),
  ('Plaine Verte Mediclinic', 'Private Mediclinic', 'Port Louis'),
  ('City Clinic', 'Private Mediclinic', NULL),
  ('Odette Leal CHC', 'Community Health Centre', 'Rose Hill'),
  ('Michael Leal CHC', 'Community Health Centre', NULL),
  ('Roche Bois CHC', 'Community Health Centre', 'Port Louis'),
  ('Pailles CHC', 'Community Health Centre', 'Port Louis'),
  ('Albion CHC', 'Community Health Centre', 'Black River'),
  ('Sainte Croix CHC', 'Community Health Centre', 'Port Louis'),
  ('Tombeau Bay CHC', 'Community Health Centre', 'Pamplemousses'),
  ('Phoenix CHC', 'Community Health Centre', 'Plaines Wilhems'),
  ('Cap Malheureux CHC', 'Community Health Centre', 'Rivière du Rempart'),
  ('Trèfles CHC', 'Community Health Centre', NULL),
  ('Pointe aux Sables CHC', 'Community Health Centre', 'Port Louis'),
  ('Bambous AHC', 'Area Health Centre', 'Black River'),
  ('Lady Twining AHC', 'Area Health Centre', 'Rose Hill'),
  ('New Grove AHC', 'Area Health Centre', 'Grand Port'),
  ('Tyack AHC', 'Area Health Centre', 'Savanne'),
  ('Bouloux AHC', 'Area Health Centre', NULL),
  ('Chemin Grenier AHC', 'Area Health Centre', 'Savanne'),
  ('Yves Cantin CHC', 'Community Health Centre', 'Black River (Bambous)'),
  ('Beau Bassin AHC', 'Area Health Centre', 'Plaines Wilhems'),
  ('Rose Hill AHC', 'Area Health Centre', 'Plaines Wilhems'),
  ('Quatre Bornes AHC', 'Area Health Centre', 'Plaines Wilhems'),
  ('St Pierre LHC', 'Area Health Centre', 'Moka'),
  ('Curepipe AHC', 'Area Health Centre', 'Plaines Wilhems'),
  ('C-Lab', 'Private Laboratory', NULL),
  ('Biosanté Laboratory', 'Private Laboratory', NULL),
  ('Novalab', 'Private Laboratory', NULL),
  ('Medisave', 'Private Laboratory', NULL),
  ('Laboratoire des Villes Soeurs', 'Private Laboratory', NULL),
  ('Clinic Muller', 'Private Laboratory', NULL)
ON CONFLICT (facility_name) DO UPDATE
  SET facility_type = EXCLUDED.facility_type,
      health_region = EXCLUDED.health_region;
